FROM node:18-alpine as node
WORKDIR /app
COPY  ./ /app
RUN npm install
RUN npm run build -- --prod

FROM nginx:1.25-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=node /app/dist/ClaroProyect /usr/share/nginx/html
